# Generated by Django 3.2.6 on 2021-08-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelnewapp', '0002_alter_place_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='blog_picturess'),
        ),
    ]
